#s line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'MaiDou' do
    
#Swift
pod 'SwiftyJSON', '~> 3.1.1'
pod 'Kingfisher', '~> 3.1.4'
pod 'SnapKit', '~> 3.0.2'
pod 'SKPhotoBrowser', :git => 'https://github.com/suzuki-0000/SKPhotoBrowser.git', :branch => 'swift3'
pod 'Toast-Swift', '2.0.0'
pod 'SDCAlertView', '~> 7.1'
pod 'ImagePicker', '~> 2.0.0'
pod 'XLActionController'

pod 'LPNetworkManager', :git => 'git@bitbucket.org:loopeer/lpnetworkmanager.git', :commit => 'b60dbda'
pod 'LPTransitions', :git => 'git@bitbucket.org:loopeer/lptransitions.git', :commit => 'c580535'
pod 'LPFramework', :git => 'git@bitbucket.org:loopeer/lpframework.git', :commit => '2d511c1'
pod 'LPFramework/PickerController', :git => 'git@bitbucket.org:loopeer/lpframework.git', :commit => '2d511c1'
pod 'LPExtensions', :git => 'git@bitbucket.org:loopeer/lpextensions.git', :commit => 'b8ebda3'
pod 'LPDebug', :git => 'git@bitbucket.org:loopeer/lpdebug.git', :commit => 'c70c0c5'
pod 'QuickForm', :git => 'git@bitbucket.org:loopeer/quickform.git', :commit => '29371e7'
pod 'KeychainAccess'

#OC
#pod 'GPUImage', '~> 0.1.7'
pod 'MJRefresh'
pod 'Qiniu'
pod 'BPushSDK', '1.4.5'

#pod 'Pingpp/Alipay', '2.2.1'
#pod 'Pingpp/Wx', '2.2.1'

pod 'UMengUShare/Social/QQ'
pod 'UMengUShare/Social/WeChat'
pod 'UMengUShare/Social/Sina'

    target 'MaiDouTests' do
        inherit! :search_paths
        # Pods for testing
    end

end

xcodeproj 'MaiDou/MaiDou.xcodeproj'

